AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'serverless-placeholder

    Sample SAM Template for serverless-placeholder

    '
Resources:
    DepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: Dependencies for placeholder app
            ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-3zq57zgujdeq/484cdb54a70a5348aaa7e2bd69b39543
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: MIT
            RetentionPolicy: Delete
        Metadata:
            SamResourceId: DepLayer
    AWSLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: AWS Dependencies for placeholder app
            ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-3zq57zgujdeq/50a86d14d017e113a240efbbf08bf402
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: MIT
            RetentionPolicy: Delete
        Metadata:
            SamResourceId: AWSLayer
    ObjectFunctionStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: https://s3.ca-central-1.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-3zq57zgujdeq/ee264c77edc11c892833f48454b468fb.template
            Parameters:
                AWSLayer:
                    Ref: AWSLayer
                DepLayer:
                    Ref: DepLayer
        Metadata:
            SamResourceId: ObjectFunctionStack
    ObjectApiStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: https://s3.ca-central-1.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-3zq57zgujdeq/c710c1f93a71ddad92be60393aec21d7.template
            Parameters:
                ObjectAdminFunctionArn:
                    Fn::GetAtt:
                        - ObjectFunctionStack
                        - Outputs.ObjectFunctionArn
        Metadata:
            SamResourceId: ObjectApiStack
