AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-placeholder

    Sample SAM Template for serverless-placeholder

Resources:
    DepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: Dependencies for placeholder app
            ContentUri: './layers/dependencies/'
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete
    AWSLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: AWS Dependencies for placeholder app
            ContentUri: './layers/aws/'
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete

    ObjectFunctionStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./templates/function/object-function.yaml
            Parameters:
                AWSLayer: !Ref AWSLayer
                DepLayer: !Ref DepLayer

    ObjectApiStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./templates/api/object-api.yaml
            Parameters:
                ObjectAdminFunctionArn: !GetAtt ObjectFunctionStack.Outputs.ObjectFunctionArn

    # UserApiStack:
    #     Type: AWS::Serverless::Application
    #     Properties:
    #         Location: ./templates/api/user-api.yaml

    # UserFunctionStack:
    #     Type: AWS::Serverless::Application
    #     Properties:
    #         Location: ./templates/function/user-function.yaml

    # ApplicationResourceGroup:
    #     Type: AWS::ResourceGroups::Group
    #     Properties:
    #         Name:
    #             Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
    #         ResourceQuery:
    #             Type: CLOUDFORMATION_STACK_1_0
    # ApplicationInsightsMonitoring:
    #     Type: AWS::ApplicationInsights::Application
    #     Properties:
    #         ResourceGroupName:
    #             Ref: ApplicationResourceGroup
    #         AutoConfigurationEnabled: true

Outputs:
    ApiURL:
        Description: 'API Gateway endpoint URL for Prod stage'
        Value: !GetAtt ObjectApiStack.Outputs.ApiURL
