AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-placeholder

    Sample SAM Template for serverless-placeholder

Resources:
    UserApiStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./templates/api/user-api.yaml

    ObjectApiStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./templates/api/object-api.yaml

    UserFunctionStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./templates/function/user-function.yaml

    ObjectFunctionStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./templates/function/object-function.yaml

    # ApplicationResourceGroup:
    #     Type: AWS::ResourceGroups::Group
    #     Properties:
    #         Name:
    #             Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
    #         ResourceQuery:
    #             Type: CLOUDFORMATION_STACK_1_0
    # ApplicationInsightsMonitoring:
    #     Type: AWS::ApplicationInsights::Application
    #     Properties:
    #         ResourceGroupName:
    #             Ref: ApplicationResourceGroup
    #         AutoConfigurationEnabled: true
