AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-placeholder

    Sample SAM Template for serverless-placeholder

Resources:
    DepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: Dependencies for placeholder app
            ContentUri: './layers/dependencies/'
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete
    AWSLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: AWS Dependencies for placeholder app
            ContentUri: './dist/layers/aws/'
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete

    ObjectStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./templates/object-stack.yaml
            Parameters:
                AWSLayer: !Ref AWSLayer
                DepLayer: !Ref DepLayer

    UserStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./templates/user-stack.yaml
            Parameters:
                AWSLayer: !Ref AWSLayer
                DepLayer: !Ref DepLayer

    # ApplicationResourceGroup:
    #     Type: AWS::ResourceGroups::Group
    #     Properties:
    #         Name:
    #             Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
    #         ResourceQuery:
    #             Type: CLOUDFORMATION_STACK_1_0
    # ApplicationInsightsMonitoring:
    #     Type: AWS::ApplicationInsights::Application
    #     Properties:
    #         ResourceGroupName:
    #             Ref: ApplicationResourceGroup
    #         AutoConfigurationEnabled: true
