AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-placeholder

    Sample SAM Template for serverless-placeholder

Parameters:
    Environment:
        Type: String
        AllowedValues: [LOCAL, DEV, PROD]
        Default: DEV

Resources:
    DepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: Dependencies for placeholder app
            ContentUri: './layers/dependencies/'
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete
    AWSLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: AWS Dependencies for placeholder app
            ContentUri: './dist/layers/aws/'
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete

    ObjectStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./templates/object-stack.yaml
            Parameters:
                AWSLayer: !Ref AWSLayer
                DepLayer: !Ref DepLayer
                Environment: !Ref Environment
            Tags:
                Environment: !Ref Environment

    UserStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./templates/user-stack.yaml
            Parameters:
                AWSLayer: !Ref AWSLayer
                DepLayer: !Ref DepLayer
                Environment: !Ref Environment
            Tags:
                Environment: !Ref Environment

    ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
            Name: serverless-placeholder
            ResourceQuery:
                Type: CLOUDFORMATION_STACK_1_0

    ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
            ResourceGroupName:
                Ref: ApplicationResourceGroup
            AutoConfigurationEnabled: true
Outputs:
    ObjectApi:
        Description: API Gateway V1 endpoint URL
        Value: !GetAtt ObjectStack.Outputs.ObjectApi
    UserApi:
        Description: API Gateway V1 endpoint URL
        Value: !GetAtt UserStack.Outputs.UserApi
