AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-placeholder object function stack

    Sample SAM Template for serverless-placeholder

Parameters:
    AWSLayer:
        Type: String
        Description: The ARN of the AWSLayer
    DepLayer:
        Type: String
        Description: The ARN of the DepLayer

Globals:
    Function:
        Timeout: 3
        MemorySize: 128
        Runtime: nodejs14.x
        Architectures:
            - x86_64
        Handler: app.lambdaHandler
        Environment:
            Variables:
                OBJECT_TABLE: !Ref ObjectTable
        Layers:
            - !Ref AWSLayer
            - !Ref DepLayer

Resources:
    ObjectTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ObjectTable
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    ObjectAdminFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../../functions/object/object-admin/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ObjectTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - uuid
                    - /opt/nodejs/dynamodb/*

Outputs:
    ObjectFunctionArn:
        Description: The ARN of the ObjectFunction
        Value: !GetAtt ObjectAdminFunction.Arn
