Globals:
    Function:
        Timeout: 3
        MemorySize: 128
        Runtime: nodejs14.x
        Architectures:
            - x86_64
        Handler: app.lambdaHandler
        Environment:
            Variables:
                OBJECT_TABLE: !Ref ObjectTable
        Layers:
            - !Ref DepLayer

Resources:
    DepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: dependencies
            Description: Dependencies for placeholder app
            ContentUri: ../../dependencies/
            CompatibleRuntimes:
                - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain

    ObjectTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ObjectTable
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    ObjectAdminFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../../functions/object/object-admin/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ObjectTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - aws-sdk
                    - uuid
