Resources:
    UserApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Dev
            DefinitionBody:
                swagger: '2.0'
                info:
                    title: User API
                paths:
                    /user-signup:
                        post:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserSignupFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'

                    /user-login:
                        post:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserLoginFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'

                    /user-admin:
                        get:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserAdminFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'
                        post:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserAdminFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'
                        put:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserAdminFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'
                        delete:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserAdminFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'

                    /user-management:
                        get:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserManagementFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'
                        delete:
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserManagementFunction.Arn}/invocations
                                passthroughBehavior: 'when_no_match'
                                httpMethod: 'POST'
                                type: 'aws_proxy'
                        /updateUser:
                            put:
                                x-amazon-apigateway-integration:
                                    uri:
                                        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserManagementFunction.Arn}/invocations
                                    passthroughBehavior: 'when_no_match'
                                    httpMethod: 'POST'
                                    type: 'aws_proxy'

                        /changePassword:
                            put:
                                x-amazon-apigateway-integration:
                                    uri:
                                        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserManagementFunction.Arn}/invocations
                                    passthroughBehavior: 'when_no_match'
                                    httpMethod: 'POST'
                                    type: 'aws_proxy'
