Globals:
    Function:
        Timeout: 3
        MemorySize: 128
        Runtime: nodejs14.x
        Architectures:
            - x86_64
        Handler: app.lambdaHandler
        Environment:
            Variables:
                USER_TABLE: !Ref UserTable
        Layers:
            - !Ref DepLayer

Resources:

    DepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: dependencies
            Description: Dependencies for placeholder app
            ContentUri: ../dependencies/
            CompatibleRuntimes:
            - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
    
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: UserTable
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: email
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: EmailIndex
                  KeySchema:
                      - AttributeName: email
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL

    UserAdminFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user-admin/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - aws-sdk
                    - bcryptjs
                    - uuid

    UserManagementFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user-management/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - aws-sdk
                    - bcryptjs
                    - uuid

    UserLoginFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user-login/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - aws-sdk
                    - bcryptjs
                    - uuid

    UserSignupFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user-signup/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - aws-sdk
                    - bcryptjs
                    - uuid
