Globals:
    Function:
        Timeout: 3
        MemorySize: 128
        Runtime: nodejs14.x
        Architectures:
            - x86_64
        Handler: app.lambdaHandler
        Environment:
            Variables:
                USER_TABLE: !Ref UserTable

Resources:
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: UserTable
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    UserAdminFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../user-admin/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts

    UserManagementFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../user-management/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts

    UserLoginFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../user-login/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts

    UserSignupFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../user-signup/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
