AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-placeholder user function stack

    Sample SAM Template for serverless-placeholder

Parameters:
    AWSLayer:
        Type: String
        Description: The ARN of the AWSLayer
    DepLayer:
        Type: String
        Description: The ARN of the DepLayer
    Environment:
        Type: String
        AllowedValues: [DEV, PROD]
        Default: DEV
Globals:
    Function:
        Timeout: 3
        MemorySize: 128
        Runtime: nodejs14.x
        Architectures:
            - x86_64
        Handler: app.lambdaHandler
        Environment:
            Variables:
                TABLE_NAME: !Ref UserTable
                ENV: !Ref Environment
        Tags:
            Environment: !Ref Environment
        Layers:
            - !Ref DepLayer
            - !Ref AWSLayer

Resources:
    UserApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            StageName: Dev
            Tags:
                Environment: !Ref Environment
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: UserTable
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: email
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: email
                  KeySchema:
                      - AttributeName: email
                        KeyType: HASH
                  Projection:
                      ProjectionType: INCLUDE
                      NonKeyAttributes:
                          - password

    UserAdminFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user/user-admin/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
            Events:
                UserAdminApi:
                    Type: HttpApi
                    Properties:
                        Path: /user-admin
                        Method: ANY
                        ApiId: !Ref UserApi

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - /opt/nodejs/dynamodb/*
                    - bcryptjs
                    - uuid

    UserManagementFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user/user-management/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
            Events:
                UserManagementApi:
                    Type: HttpApi
                    Properties:
                        Path: /user-management
                        Method: ANY
                        ApiId: !Ref UserApi

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - /opt/nodejs/dynamodb/*
                    - bcryptjs
                    - uuid

    UserObjectFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user/user-object/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
            Events:
                UserObjectApi:
                    Type: HttpApi
                    Properties:
                        Path: /user-object
                        Method: ANY
                        ApiId: !Ref UserApi

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - /opt/nodejs/dynamodb/*

    UserLoginFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user/user-login/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
            Events:
                UserLoginApi:
                    Type: HttpApi
                    Properties:
                        Path: /user-login
                        Method: POST
                        ApiId: !Ref UserApi

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - /opt/nodejs/dynamodb/*
                    - bcryptjs
                    - uuid

    UserSignupFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/user/user-signup/
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
            Events:
                UserSignupApi:
                    Type: HttpApi
                    Properties:
                        Path: /user-signup
                        Method: POST
                        ApiId: !Ref UserApi

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                EntryPoints:
                    - app.ts
                External:
                    - /opt/nodejs/dynamodb/*
                    - bcryptjs
                    - uuid
Outputs:
    UserApi:
        Description: 'API Gateway endpoint URL for Prod stage for UserApi function'
        Value: !Sub 'https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/'
