Resources:
    UserApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Dev
            DefinitionBody:
                swagger: '2.0'
                info:
                    title: User API
                common-integration: &common-integration
                    passthroughBehavior: 'when_no_match'
                    httpMethod: 'POST'
                    type: 'aws_proxy'
                managment-uri: &managment-uri
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserManagementFunction.Arn}/invocations
                objectManagment-uri: &objectManagment-uri
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserObjectFunction.Arn}/invocations
                paths:
                    /user-signup:
                        post:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserSignupFunction.Arn}/invocations

                    /user-login:
                        post:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserLoginFunction.Arn}/invocations

                    /user-admin:
                        x-amazon-apigateway-any-method:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserAdminFunction.Arn}/invocations

                    /user-management:
                        get:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *managment-uri
                        delete:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *managment-uri

                    /user-management/updateUser:
                        put:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *managment-uri

                    /user-management/changePassword:
                        put:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *managment-uri

                    /user-object:
                        get:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *objectManagment-uri

                    /user-object/addObject:
                        put:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *objectManagment-uri

                    /user-object/removeObject:
                        put:
                            x-amazon-apigateway-integration:
                                <<: *common-integration
                                uri: *objectManagment-uri
